### ISSUE TITLE
how to   define  image id to replace?

### ISSUE THREAD

**Issue by xjdata** [Raaghu1987/docxTemplateInPHP#5]
thank you.

**Comment by Raaghu** [comment]
Rightclick on the dummy image and select size, 
in alttext tab , specify the image id to be replaced

![image](https://cloud.githubusercontent.com/assets/8255650/15530604/10978e9c-2273-11e6-974f-3e6a6b634051.png)

**Comment by xjdata** [comment]
thank you.
