### ISSUE TITLE
Foreach for docx

### ISSUE THREAD

**Issue by mrmoonlv** [Raaghu1987/docxTemplateInPHP#6]
In _test/RepeatRowTest/RepeatRowTest.php_ exist foreach for xml output.
How to use foreach for doxc output?
Thanks.

**Comment by mrmoonlv** [comment]
Found: 
In docx **[item;repeat=items;repeatType=row]** need put in table like bloke for loop.

**Comment by diogomachado** [comment]
For me, this work:

**[item;repeat=items;repeatType=row][item.name]**
