### ISSUE TITLE
How to add hyperlink 

### ISSUE THREAD

**Issue by souvik79** [Raaghu1987/docxTemplateInPHP#7]
Hi,

Could you let me know how to add hyperlink

regards

**Comment by Raaghu** [comment]
Hi souvik 
I think hyperlinks are not handled currently , will add this feature shorty , stay tuned

**Comment by Raaghu** [comment]
@souvik79 
added hyperlink support in [v0.1.2](https://github.com/iCircle/docxTemplateInPHP/releases/tag/v0.1.2)
check the [Hyprelink Test](https://github.com/iCircle/docxTemplateInPHP/tree/v0.1/tests/Template/Docx/HyperlinkTest) for example
