### ISSUE TITLE
Composer require fails?

### ISSUE THREAD

**Issue by kstenschke** [Raaghu1987/docxTemplateInPHP#8]
I tried to install docxTemplateInPHP via composer with variations of

> composer require icircle/docx-template-in-php

 which all failed with error messages like: 

> Your requirements could not be resolved to an installable set of packages.
> ...
> Installation failed, reverting ./composer.json to its original content.

**Comment by Raaghu** [comment]
@kstenschke please attach complete log , or email me at raaghu1987@gmail.com

**Comment by Raaghu** [comment]
closing this issue  , as i did not get enough information to anaylze this
