### ISSUE TITLE
How build a repeat list?

### ISSUE THREAD

**Issue by diogomachado** [Raaghu1987/docxTemplateInPHP#9]
I try create **docx** with repeat list users:

Example:
- Name 1
- Name 2
- Name 3

But without success, you can I help-me please?

**Comment by Raaghu** [comment]
please use the syntax 
[item;repeat=record.list1;repeatType=list][item.name]

please see the [repeatListTest](https://github.com/iCircle/docxTemplateInPHP/tree/master/tests/Template/Docx/RepeatListTest)
for example
